# Generated by Django 5.1.2 on 2024-11-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winecellar',
            name='total_spots',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
