# Generated by Django 5.1.2 on 2024-10-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winecellar',
            name='join_us',
            field=models.TextField(default='Join us for an unforgettable experience!'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winecellar',
            name='what_to_expect',
            field=models.TextField(default='Join us for an unforgettable experience!'),
            preserve_default=False,
        ),
    ]
