# Generated by Django 5.1.2 on 2024-10-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_winecellar_join_us_winecellar_what_to_expect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winecellar',
            old_name='join_us',
            new_name='join_us_for',
        ),
    ]
